# Generated by Django 2.2.13 on 2020-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
